# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  clave: 2dd1be9903feb29
  codigo: nfg
  max_num_login_fails: -1
  password_expire: -1
  titulo: nosfaltagente
  tema: nfg

  .array:
    assets:
      javascripts: []
      stylesheets: [ native/css/default.css, native/css/admin.css ]
      
  mantenimiento:
    activo: 0
    url_modulo: sftGestorErrores
    url_accion: mantenimiento
    
  ventanas_emergentes:
    parametros: 'width=600,height=400,left=400,top=200,resizable=yes,scrollbars=yes'
    
  registro:
    mail_from: 'nosfaltagente@nosfaltagente.com'
    mail_subject: 'Sistema de registro de nosfaltagente.com'
    mail_body: 'Ha solicitado darse de alta en nosfaltagente.com. Pulse en el siguiente enlace para completar el registro.\n\nUn Saludo. El equipo de nosfaltagente.com' 