<?php


/**
 * Skeleton subclass for performing query and update operations on the 'bol_habilidad' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun May 20 14:21:26 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BolHabilidadPeer extends BaseBolHabilidadPeer
{
    static public function retrieveForAutoSelect($q)
    {
        $oCriteria = new Criteria();
        $oCriteria->add(BolHabilidadPeer::NOMBRE, '%'.$q.'%', Criteria::LIKE);
        $oCriteria->addAscendingOrderByColumn(BolHabilidadPeer::NOMBRE);

        $tHabilidad = array();
        foreach (BolHabilidadPeer::doSelect($oCriteria) as $oHabilidad)
        {
            $tHabilidad[$oHabilidad->getId()] = $oHabilidad->getNombre();
        }

        return $tHabilidad;
    }
  

} // BolHabilidadPeer
