generator:
  class: sfPropelGenerator
  param:
    model_class:           NfgConvocatoria
    theme:                 nosfaltauno
    non_verbose_templates: true
    with_show:             false
    singular:              NfgConvocatoria
    plural:                NfgConvocatorias
    route_prefix:          nfg_convocatoria
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   false

    config:
      actions: ~
      fields:
        act: {label: Actividad}
        diahora: {label: Dia/Hora}
        faltan: {label: Me Faltan}
        id_actividad: {label: "¿Qué?" }
        id_lugar_ini: {label: ¿Dónde? }
        NfgLugarRelatedByIdLugarIni: {label: ¿Dónde? }
        NfgLugarRelatedByIdLugarFin: {label: ¿Hasta dónde? }
        fecha_ini: {label: ¿Cuándo?}
        fecha_fin: {label: ¿Hasta cuándo?}
        notas: {label: ¿Algo más? }
        NfgActividad: {label: ¿Qué? }
        NfgLugar: {label: ¿Dónde? }
        fechaConvocatoria: {label: ¿Cuándo? }
        participantes_min: {help: "deja esta casilla en blanco si no se requiere un número mínimo de participantes"}
        participantes_max: {help: "deja esta casilla en blanco si no hay límite en el número de personas que pueden apuntarse"}
        privada: {label: Privado, help: "si marcas la convocatoria como privada, solamente podrán verla aquellas personas a las que tú invites"}
      list:
        title: "Actividades"
        display: [=NfgActividad, =NfgLugarRelatedByIdLugarIni, =localidad, =fechaConvocatoria, =textoFaltan]
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:  {class: false}
      form:    ~
      edit:
        title: Editar Convocatoria del dia %%fecha_ini%%
        display: [id_lugar_ini, fecha_ini, hora_ini, hora_fin, notas, participantes_min, participantes_max, participantes_ini, privada]
        actions:
            _save: ~
            _delete: ~
      new:
        title: Nueva convocatoria
        display: [id_actividad, id_lugar_ini, id_lugar_fin, fecha_ini,fecha_fin, hora_ini, hora_fin, notas, participantes_min, participantes_max, privada]
        actions:
            _save: ~