generator:
  class: sfPropelGenerator
  param:
    model_class:           NfgLugar
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              NfgLugar
    plural:                NfgLugars
    route_prefix:          nfg_lugar
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
        nombre: {help: "Ponle un nombre a este lugar"}
        direccion: {label: Dirección, help: "Puedes escribir una dirección para buscarla en el mapa"}
        id_localidad: {label: Localidad}
        particular: {help: "Marca esta casilla si este lugar es particular o privado y no deseas que salga en las búsquedas a otros usuarios"}
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:
        title: Nuevo lugar
        actions:
          _save: ~
