<?php


/**
 * This class defines the structure of the 'sft_acceso_ambito' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:06 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sftGuardPlugin.lib.model.map
 */
class SftAccesoAmbitoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sftGuardPlugin.lib.model.map.SftAccesoAmbitoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sft_acceso_ambito');
		$this->setPhpName('SftAccesoAmbito');
		$this->setClassname('SftAccesoAmbito');
		$this->setPackage('plugins.sftGuardPlugin.lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('ID_ACCESO', 'IdAcceso', 'INTEGER' , 'sft_accesos', 'ID', true, null, null);
		$this->addForeignPrimaryKey('ID_AMBITO', 'IdAmbito', 'INTEGER' , 'sft_ambitos', 'ID', true, null, null);
		$this->addColumn('FECHAINICIO', 'Fechainicio', 'DATE', false, null, null);
		$this->addColumn('FECHAFIN', 'Fechafin', 'DATE', false, null, null);
		$this->addColumn('FECHACADUCIDAD', 'Fechacaducidad', 'DATE', false, null, null);
		$this->addColumn('ESTADO', 'Estado', 'VARCHAR', true, 255, 'ACTIVO');
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SftAcceso', 'SftAcceso', RelationMap::MANY_TO_ONE, array('id_acceso' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SftAmbito', 'SftAmbito', RelationMap::MANY_TO_ONE, array('id_ambito' => 'id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SftAccesoAmbitoTableMap
