<?php


/**
 * This class defines the structure of the 'sft_perfiles' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:12 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sftGuardPlugin.lib.model.map
 */
class SftPerfilTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sftGuardPlugin.lib.model.map.SftPerfilTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sft_perfiles');
		$this->setPhpName('SftPerfil');
		$this->setClassname('SftPerfil');
		$this->setPackage('plugins.sftGuardPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('ID_UO', 'IdUo', 'INTEGER', 'sft_uos', 'ID', false, null, null);
		$this->addColumn('CODIGO', 'Codigo', 'VARCHAR', true, 255, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addForeignKey('ID_AMBITOTIPO', 'IdAmbitotipo', 'INTEGER', 'sft_ambitostipos', 'ID', false, null, null);
		$this->addColumn('MENU', 'Menu', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SftUo', 'SftUo', RelationMap::MANY_TO_ONE, array('id_uo' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SftAmbitoTipo', 'SftAmbitoTipo', RelationMap::MANY_TO_ONE, array('id_ambitotipo' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('SftAcceso', 'SftAcceso', RelationMap::ONE_TO_MANY, array('id' => 'id_perfil', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('SftConfPersonal', 'SftConfPersonal', RelationMap::ONE_TO_MANY, array('id' => 'id_perfil', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SftPerfilCredencial', 'SftPerfilCredencial', RelationMap::ONE_TO_MANY, array('id' => 'id_perfil', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SftPerfilI18n', 'SftPerfilI18n', RelationMap::ONE_TO_MANY, array('id' => 'id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
			'symfony_i18n' => array('i18n_table' => 'sft_perfiles_i18n', ),
		);
	} // getBehaviors()

} // SftPerfilTableMap
