<?php


/**
 * This class defines the structure of the 'sft_personas' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:12 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sftGuardPlugin.lib.model.map
 */
class SftPersonaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sftGuardPlugin.lib.model.map.SftPersonaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sft_personas');
		$this->setPhpName('SftPersona');
		$this->setClassname('SftPersona');
		$this->setPackage('plugins.sftGuardPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', true, 40, null);
		$this->addColumn('APELLIDO1', 'Apellido1', 'VARCHAR', false, 40, null);
		$this->addColumn('APELLIDO2', 'Apellido2', 'VARCHAR', false, 40, null);
		$this->addForeignKey('ID_TIPODOCIDENTIFICACION', 'IdTipodocidentificacion', 'INTEGER', 'sft_tiposdocidentificacion', 'ID', false, null, null);
		$this->addColumn('DOCIDENTIFICACION', 'Docidentificacion', 'VARCHAR', false, 32, null);
		$this->addForeignKey('ID_PAISDOCIDENTIFICACION', 'IdPaisdocidentificacion', 'INTEGER', 'gen_paises', 'ID', false, null, null);
		$this->addColumn('SEXO', 'Sexo', 'VARCHAR', false, 1, null);
		$this->addColumn('FECHANACIMIENTO', 'Fechanacimiento', 'DATE', false, null, null);
		$this->addColumn('OBSERVACIONES', 'Observaciones', 'VARCHAR', false, 255, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('PROFESION', 'Profesion', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SftTipoDocIdentificacion', 'SftTipoDocIdentificacion', RelationMap::MANY_TO_ONE, array('id_tipodocidentificacion' => 'id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('GenPais', 'GenPais', RelationMap::MANY_TO_ONE, array('id_paisdocidentificacion' => 'id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('SftOrganismo', 'SftOrganismo', RelationMap::ONE_TO_MANY, array('id' => 'id_contacto', ), 'SET NULL', 'CASCADE');
    $this->addRelation('SftUsuario', 'SftUsuario', RelationMap::ONE_TO_MANY, array('id' => 'id_persona', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // SftPersonaTableMap
