<?php


/**
 * This class defines the structure of the 'sft_perfil_credencial' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:11 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sftGuardPlugin.lib.model.map
 */
class SftPerfilCredencialTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sftGuardPlugin.lib.model.map.SftPerfilCredencialTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sft_perfil_credencial');
		$this->setPhpName('SftPerfilCredencial');
		$this->setClassname('SftPerfilCredencial');
		$this->setPackage('plugins.sftGuardPlugin.lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('ID_PERFIL', 'IdPerfil', 'INTEGER' , 'sft_perfiles', 'ID', true, null, null);
		$this->addForeignPrimaryKey('ID_CREDENCIAL', 'IdCredencial', 'INTEGER' , 'sft_credenciales', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SftPerfil', 'SftPerfil', RelationMap::MANY_TO_ONE, array('id_perfil' => 'id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('SftCredencial', 'SftCredencial', RelationMap::MANY_TO_ONE, array('id_credencial' => 'id', ), 'CASCADE', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SftPerfilCredencialTableMap
