<?php


/**
 * This class defines the structure of the 'sft_usu_atributos' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:16 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sftGuardPlugin.lib.model.map
 */
class SftUsuAtributoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sftGuardPlugin.lib.model.map.SftUsuAtributoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sft_usu_atributos');
		$this->setPhpName('SftUsuAtributo');
		$this->setClassname('SftUsuAtributo');
		$this->setPackage('plugins.sftGuardPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', true, 255, null);
		$this->addColumn('DESCRIPCION', 'Descripcion', 'VARCHAR', false, 255, null);
		$this->addColumn('FORMATO', 'Formato', 'VARCHAR', false, 255, null);
		$this->addColumn('RELEVANCIA', 'Relevancia', 'VARCHAR', false, 255, null);
		$this->addColumn('ORIGEN', 'Origen', 'VARCHAR', false, 255, null);
		$this->addColumn('OID', 'Oid', 'VARCHAR', false, 255, null);
		$this->addColumn('URN', 'Urn', 'VARCHAR', false, 255, null);
		$this->addColumn('SINTAXIS_LDAP', 'SintaxisLdap', 'VARCHAR', false, 255, null);
		$this->addColumn('INDEXADO', 'Indexado', 'VARCHAR', false, 255, null);
		$this->addColumn('MULTIVALUADO', 'Multivaluado', 'TINYINT', false, null, null);
		$this->addColumn('EJEMPLO', 'Ejemplo', 'VARCHAR', false, 255, null);
		$this->addColumn('NOTAS', 'Notas', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SftUsuAtributoValor', 'SftUsuAtributoValor', RelationMap::ONE_TO_MANY, array('id' => 'id_usu_atributo', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SftUsuAtributoTableMap
