<?php

/**
 * Base class that represents a row from the 'sft_perfiles' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:12 2012
 *
 * @package    plugins.sftGuardPlugin.lib.model.om
 */
abstract class BaseSftPerfil extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SftPerfilPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the id_uo field.
	 * @var        int
	 */
	protected $id_uo;

	/**
	 * The value for the codigo field.
	 * @var        string
	 */
	protected $codigo;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the id_ambitotipo field.
	 * @var        int
	 */
	protected $id_ambitotipo;

	/**
	 * The value for the menu field.
	 * @var        string
	 */
	protected $menu;

	/**
	 * @var        SftUo
	 */
	protected $aSftUo;

	/**
	 * @var        SftAmbitoTipo
	 */
	protected $aSftAmbitoTipo;

	/**
	 * @var        array SftAcceso[] Collection to store aggregation of SftAcceso objects.
	 */
	protected $collSftAccesos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSftAccesos.
	 */
	private $lastSftAccesoCriteria = null;

	/**
	 * @var        array SftConfPersonal[] Collection to store aggregation of SftConfPersonal objects.
	 */
	protected $collSftConfPersonals;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSftConfPersonals.
	 */
	private $lastSftConfPersonalCriteria = null;

	/**
	 * @var        array SftPerfilCredencial[] Collection to store aggregation of SftPerfilCredencial objects.
	 */
	protected $collSftPerfilCredencials;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSftPerfilCredencials.
	 */
	private $lastSftPerfilCredencialCriteria = null;

	/**
	 * @var        array SftPerfilI18n[] Collection to store aggregation of SftPerfilI18n objects.
	 */
	protected $collSftPerfilI18ns;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSftPerfilI18ns.
	 */
	private $lastSftPerfilI18nCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SftPerfilPeer';

	// symfony_i18n behavior
	
	/**
	 * @var string The value for the culture field
	 */
	protected $culture = null;
	
	/**
	 * @var array Current I18N objects
	 */
	protected $current_i18n = array();

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [id_uo] column value.
	 * 
	 * @return     int
	 */
	public function getIdUo()
	{
		return $this->id_uo;
	}

	/**
	 * Get the [codigo] column value.
	 * 
	 * @return     string
	 */
	public function getCodigo()
	{
		return $this->codigo;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [id_ambitotipo] column value.
	 * 
	 * @return     int
	 */
	public function getIdAmbitotipo()
	{
		return $this->id_ambitotipo;
	}

	/**
	 * Get the [menu] column value.
	 * 
	 * @return     string
	 */
	public function getMenu()
	{
		return $this->menu;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     SftPerfil The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SftPerfilPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [id_uo] column.
	 * 
	 * @param      int $v new value
	 * @return     SftPerfil The current object (for fluent API support)
	 */
	public function setIdUo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_uo !== $v) {
			$this->id_uo = $v;
			$this->modifiedColumns[] = SftPerfilPeer::ID_UO;
		}

		if ($this->aSftUo !== null && $this->aSftUo->getId() !== $v) {
			$this->aSftUo = null;
		}

		return $this;
	} // setIdUo()

	/**
	 * Set the value of [codigo] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPerfil The current object (for fluent API support)
	 */
	public function setCodigo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->codigo !== $v) {
			$this->codigo = $v;
			$this->modifiedColumns[] = SftPerfilPeer::CODIGO;
		}

		return $this;
	} // setCodigo()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SftPerfil The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SftPerfilPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SftPerfil The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SftPerfilPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [id_ambitotipo] column.
	 * 
	 * @param      int $v new value
	 * @return     SftPerfil The current object (for fluent API support)
	 */
	public function setIdAmbitotipo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_ambitotipo !== $v) {
			$this->id_ambitotipo = $v;
			$this->modifiedColumns[] = SftPerfilPeer::ID_AMBITOTIPO;
		}

		if ($this->aSftAmbitoTipo !== null && $this->aSftAmbitoTipo->getId() !== $v) {
			$this->aSftAmbitoTipo = null;
		}

		return $this;
	} // setIdAmbitotipo()

	/**
	 * Set the value of [menu] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPerfil The current object (for fluent API support)
	 */
	public function setMenu($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->menu !== $v) {
			$this->menu = $v;
			$this->modifiedColumns[] = SftPerfilPeer::MENU;
		}

		return $this;
	} // setMenu()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_uo = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->codigo = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->created_at = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->updated_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->id_ambitotipo = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->menu = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = SftPerfilPeer::NUM_COLUMNS - SftPerfilPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating SftPerfil object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSftUo !== null && $this->id_uo !== $this->aSftUo->getId()) {
			$this->aSftUo = null;
		}
		if ($this->aSftAmbitoTipo !== null && $this->id_ambitotipo !== $this->aSftAmbitoTipo->getId()) {
			$this->aSftAmbitoTipo = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftPerfilPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SftPerfilPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSftUo = null;
			$this->aSftAmbitoTipo = null;
			$this->collSftAccesos = null;
			$this->lastSftAccesoCriteria = null;

			$this->collSftConfPersonals = null;
			$this->lastSftConfPersonalCriteria = null;

			$this->collSftPerfilCredencials = null;
			$this->lastSftPerfilCredencialCriteria = null;

			$this->collSftPerfilI18ns = null;
			$this->lastSftPerfilI18nCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftPerfilPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSftPerfil:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				SftPerfilPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSftPerfil:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftPerfilPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSftPerfil:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(SftPerfilPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(SftPerfilPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSftPerfil:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SftPerfilPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSftUo !== null) {
				if ($this->aSftUo->isModified() || $this->aSftUo->isNew()) {
					$affectedRows += $this->aSftUo->save($con);
				}
				$this->setSftUo($this->aSftUo);
			}

			if ($this->aSftAmbitoTipo !== null) {
				if ($this->aSftAmbitoTipo->isModified() || $this->aSftAmbitoTipo->isNew()) {
					$affectedRows += $this->aSftAmbitoTipo->save($con);
				}
				$this->setSftAmbitoTipo($this->aSftAmbitoTipo);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SftPerfilPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SftPerfilPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SftPerfilPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collSftAccesos !== null) {
				foreach ($this->collSftAccesos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSftConfPersonals !== null) {
				foreach ($this->collSftConfPersonals as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSftPerfilCredencials !== null) {
				foreach ($this->collSftPerfilCredencials as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSftPerfilI18ns !== null) {
				foreach ($this->collSftPerfilI18ns as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSftUo !== null) {
				if (!$this->aSftUo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSftUo->getValidationFailures());
				}
			}

			if ($this->aSftAmbitoTipo !== null) {
				if (!$this->aSftAmbitoTipo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSftAmbitoTipo->getValidationFailures());
				}
			}


			if (($retval = SftPerfilPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collSftAccesos !== null) {
					foreach ($this->collSftAccesos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSftConfPersonals !== null) {
					foreach ($this->collSftConfPersonals as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSftPerfilCredencials !== null) {
					foreach ($this->collSftPerfilCredencials as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSftPerfilI18ns !== null) {
					foreach ($this->collSftPerfilI18ns as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SftPerfilPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getIdUo();
				break;
			case 2:
				return $this->getCodigo();
				break;
			case 3:
				return $this->getCreatedAt();
				break;
			case 4:
				return $this->getUpdatedAt();
				break;
			case 5:
				return $this->getIdAmbitotipo();
				break;
			case 6:
				return $this->getMenu();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SftPerfilPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getIdUo(),
			$keys[2] => $this->getCodigo(),
			$keys[3] => $this->getCreatedAt(),
			$keys[4] => $this->getUpdatedAt(),
			$keys[5] => $this->getIdAmbitotipo(),
			$keys[6] => $this->getMenu(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SftPerfilPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setIdUo($value);
				break;
			case 2:
				$this->setCodigo($value);
				break;
			case 3:
				$this->setCreatedAt($value);
				break;
			case 4:
				$this->setUpdatedAt($value);
				break;
			case 5:
				$this->setIdAmbitotipo($value);
				break;
			case 6:
				$this->setMenu($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SftPerfilPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdUo($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCodigo($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCreatedAt($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUpdatedAt($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setIdAmbitotipo($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMenu($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);

		if ($this->isColumnModified(SftPerfilPeer::ID)) $criteria->add(SftPerfilPeer::ID, $this->id);
		if ($this->isColumnModified(SftPerfilPeer::ID_UO)) $criteria->add(SftPerfilPeer::ID_UO, $this->id_uo);
		if ($this->isColumnModified(SftPerfilPeer::CODIGO)) $criteria->add(SftPerfilPeer::CODIGO, $this->codigo);
		if ($this->isColumnModified(SftPerfilPeer::CREATED_AT)) $criteria->add(SftPerfilPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(SftPerfilPeer::UPDATED_AT)) $criteria->add(SftPerfilPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(SftPerfilPeer::ID_AMBITOTIPO)) $criteria->add(SftPerfilPeer::ID_AMBITOTIPO, $this->id_ambitotipo);
		if ($this->isColumnModified(SftPerfilPeer::MENU)) $criteria->add(SftPerfilPeer::MENU, $this->menu);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);

		$criteria->add(SftPerfilPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of SftPerfil (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdUo($this->id_uo);

		$copyObj->setCodigo($this->codigo);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setIdAmbitotipo($this->id_ambitotipo);

		$copyObj->setMenu($this->menu);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getSftAccesos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSftAcceso($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSftConfPersonals() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSftConfPersonal($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSftPerfilCredencials() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSftPerfilCredencial($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSftPerfilI18ns() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSftPerfilI18n($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     SftPerfil Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SftPerfilPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SftPerfilPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a SftUo object.
	 *
	 * @param      SftUo $v
	 * @return     SftPerfil The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSftUo(SftUo $v = null)
	{
		if ($v === null) {
			$this->setIdUo(NULL);
		} else {
			$this->setIdUo($v->getId());
		}

		$this->aSftUo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SftUo object, it will not be re-added.
		if ($v !== null) {
			$v->addSftPerfil($this);
		}

		return $this;
	}


	/**
	 * Get the associated SftUo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SftUo The associated SftUo object.
	 * @throws     PropelException
	 */
	public function getSftUo(PropelPDO $con = null)
	{
		if ($this->aSftUo === null && ($this->id_uo !== null)) {
			$this->aSftUo = SftUoPeer::retrieveByPk($this->id_uo);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSftUo->addSftPerfils($this);
			 */
		}
		return $this->aSftUo;
	}

	/**
	 * Declares an association between this object and a SftAmbitoTipo object.
	 *
	 * @param      SftAmbitoTipo $v
	 * @return     SftPerfil The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSftAmbitoTipo(SftAmbitoTipo $v = null)
	{
		if ($v === null) {
			$this->setIdAmbitotipo(NULL);
		} else {
			$this->setIdAmbitotipo($v->getId());
		}

		$this->aSftAmbitoTipo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SftAmbitoTipo object, it will not be re-added.
		if ($v !== null) {
			$v->addSftPerfil($this);
		}

		return $this;
	}


	/**
	 * Get the associated SftAmbitoTipo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SftAmbitoTipo The associated SftAmbitoTipo object.
	 * @throws     PropelException
	 */
	public function getSftAmbitoTipo(PropelPDO $con = null)
	{
		if ($this->aSftAmbitoTipo === null && ($this->id_ambitotipo !== null)) {
			$this->aSftAmbitoTipo = SftAmbitoTipoPeer::retrieveByPk($this->id_ambitotipo);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSftAmbitoTipo->addSftPerfils($this);
			 */
		}
		return $this->aSftAmbitoTipo;
	}

	/**
	 * Clears out the collSftAccesos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSftAccesos()
	 */
	public function clearSftAccesos()
	{
		$this->collSftAccesos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSftAccesos collection (array).
	 *
	 * By default this just sets the collSftAccesos collection to an empty array (like clearcollSftAccesos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSftAccesos()
	{
		$this->collSftAccesos = array();
	}

	/**
	 * Gets an array of SftAcceso objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SftPerfil has previously been saved, it will retrieve
	 * related SftAccesos from storage. If this SftPerfil is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SftAcceso[]
	 * @throws     PropelException
	 */
	public function getSftAccesos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftAccesos === null) {
			if ($this->isNew()) {
			   $this->collSftAccesos = array();
			} else {

				$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

				SftAccesoPeer::addSelectColumns($criteria);
				$this->collSftAccesos = SftAccesoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

				SftAccesoPeer::addSelectColumns($criteria);
				if (!isset($this->lastSftAccesoCriteria) || !$this->lastSftAccesoCriteria->equals($criteria)) {
					$this->collSftAccesos = SftAccesoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSftAccesoCriteria = $criteria;
		return $this->collSftAccesos;
	}

	/**
	 * Returns the number of related SftAcceso objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SftAcceso objects.
	 * @throws     PropelException
	 */
	public function countSftAccesos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSftAccesos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

				$count = SftAccesoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

				if (!isset($this->lastSftAccesoCriteria) || !$this->lastSftAccesoCriteria->equals($criteria)) {
					$count = SftAccesoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSftAccesos);
				}
			} else {
				$count = count($this->collSftAccesos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SftAcceso object to this object
	 * through the SftAcceso foreign key attribute.
	 *
	 * @param      SftAcceso $l SftAcceso
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSftAcceso(SftAcceso $l)
	{
		if ($this->collSftAccesos === null) {
			$this->initSftAccesos();
		}
		if (!in_array($l, $this->collSftAccesos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSftAccesos, $l);
			$l->setSftPerfil($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPerfil is new, it will return
	 * an empty collection; or if this SftPerfil has previously
	 * been saved, it will retrieve related SftAccesos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPerfil.
	 */
	public function getSftAccesosJoinSftUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftAccesos === null) {
			if ($this->isNew()) {
				$this->collSftAccesos = array();
			} else {

				$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

				$this->collSftAccesos = SftAccesoPeer::doSelectJoinSftUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

			if (!isset($this->lastSftAccesoCriteria) || !$this->lastSftAccesoCriteria->equals($criteria)) {
				$this->collSftAccesos = SftAccesoPeer::doSelectJoinSftUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftAccesoCriteria = $criteria;

		return $this->collSftAccesos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPerfil is new, it will return
	 * an empty collection; or if this SftPerfil has previously
	 * been saved, it will retrieve related SftAccesos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPerfil.
	 */
	public function getSftAccesosJoinSftAccesoRelatedByIdDelega($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftAccesos === null) {
			if ($this->isNew()) {
				$this->collSftAccesos = array();
			} else {

				$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

				$this->collSftAccesos = SftAccesoPeer::doSelectJoinSftAccesoRelatedByIdDelega($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftAccesoPeer::ID_PERFIL, $this->id);

			if (!isset($this->lastSftAccesoCriteria) || !$this->lastSftAccesoCriteria->equals($criteria)) {
				$this->collSftAccesos = SftAccesoPeer::doSelectJoinSftAccesoRelatedByIdDelega($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftAccesoCriteria = $criteria;

		return $this->collSftAccesos;
	}

	/**
	 * Clears out the collSftConfPersonals collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSftConfPersonals()
	 */
	public function clearSftConfPersonals()
	{
		$this->collSftConfPersonals = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSftConfPersonals collection (array).
	 *
	 * By default this just sets the collSftConfPersonals collection to an empty array (like clearcollSftConfPersonals());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSftConfPersonals()
	{
		$this->collSftConfPersonals = array();
	}

	/**
	 * Gets an array of SftConfPersonal objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SftPerfil has previously been saved, it will retrieve
	 * related SftConfPersonals from storage. If this SftPerfil is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SftConfPersonal[]
	 * @throws     PropelException
	 */
	public function getSftConfPersonals($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftConfPersonals === null) {
			if ($this->isNew()) {
			   $this->collSftConfPersonals = array();
			} else {

				$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

				SftConfPersonalPeer::addSelectColumns($criteria);
				$this->collSftConfPersonals = SftConfPersonalPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

				SftConfPersonalPeer::addSelectColumns($criteria);
				if (!isset($this->lastSftConfPersonalCriteria) || !$this->lastSftConfPersonalCriteria->equals($criteria)) {
					$this->collSftConfPersonals = SftConfPersonalPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSftConfPersonalCriteria = $criteria;
		return $this->collSftConfPersonals;
	}

	/**
	 * Returns the number of related SftConfPersonal objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SftConfPersonal objects.
	 * @throws     PropelException
	 */
	public function countSftConfPersonals(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSftConfPersonals === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

				$count = SftConfPersonalPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

				if (!isset($this->lastSftConfPersonalCriteria) || !$this->lastSftConfPersonalCriteria->equals($criteria)) {
					$count = SftConfPersonalPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSftConfPersonals);
				}
			} else {
				$count = count($this->collSftConfPersonals);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SftConfPersonal object to this object
	 * through the SftConfPersonal foreign key attribute.
	 *
	 * @param      SftConfPersonal $l SftConfPersonal
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSftConfPersonal(SftConfPersonal $l)
	{
		if ($this->collSftConfPersonals === null) {
			$this->initSftConfPersonals();
		}
		if (!in_array($l, $this->collSftConfPersonals, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSftConfPersonals, $l);
			$l->setSftPerfil($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPerfil is new, it will return
	 * an empty collection; or if this SftPerfil has previously
	 * been saved, it will retrieve related SftConfPersonals from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPerfil.
	 */
	public function getSftConfPersonalsJoinSftUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftConfPersonals === null) {
			if ($this->isNew()) {
				$this->collSftConfPersonals = array();
			} else {

				$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

				$this->collSftConfPersonals = SftConfPersonalPeer::doSelectJoinSftUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

			if (!isset($this->lastSftConfPersonalCriteria) || !$this->lastSftConfPersonalCriteria->equals($criteria)) {
				$this->collSftConfPersonals = SftConfPersonalPeer::doSelectJoinSftUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftConfPersonalCriteria = $criteria;

		return $this->collSftConfPersonals;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPerfil is new, it will return
	 * an empty collection; or if this SftPerfil has previously
	 * been saved, it will retrieve related SftConfPersonals from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPerfil.
	 */
	public function getSftConfPersonalsJoinSftAplicacion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftConfPersonals === null) {
			if ($this->isNew()) {
				$this->collSftConfPersonals = array();
			} else {

				$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

				$this->collSftConfPersonals = SftConfPersonalPeer::doSelectJoinSftAplicacion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

			if (!isset($this->lastSftConfPersonalCriteria) || !$this->lastSftConfPersonalCriteria->equals($criteria)) {
				$this->collSftConfPersonals = SftConfPersonalPeer::doSelectJoinSftAplicacion($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftConfPersonalCriteria = $criteria;

		return $this->collSftConfPersonals;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPerfil is new, it will return
	 * an empty collection; or if this SftPerfil has previously
	 * been saved, it will retrieve related SftConfPersonals from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPerfil.
	 */
	public function getSftConfPersonalsJoinSftPeriodo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftConfPersonals === null) {
			if ($this->isNew()) {
				$this->collSftConfPersonals = array();
			} else {

				$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

				$this->collSftConfPersonals = SftConfPersonalPeer::doSelectJoinSftPeriodo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftConfPersonalPeer::ID_PERFIL, $this->id);

			if (!isset($this->lastSftConfPersonalCriteria) || !$this->lastSftConfPersonalCriteria->equals($criteria)) {
				$this->collSftConfPersonals = SftConfPersonalPeer::doSelectJoinSftPeriodo($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftConfPersonalCriteria = $criteria;

		return $this->collSftConfPersonals;
	}

	/**
	 * Clears out the collSftPerfilCredencials collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSftPerfilCredencials()
	 */
	public function clearSftPerfilCredencials()
	{
		$this->collSftPerfilCredencials = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSftPerfilCredencials collection (array).
	 *
	 * By default this just sets the collSftPerfilCredencials collection to an empty array (like clearcollSftPerfilCredencials());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSftPerfilCredencials()
	{
		$this->collSftPerfilCredencials = array();
	}

	/**
	 * Gets an array of SftPerfilCredencial objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SftPerfil has previously been saved, it will retrieve
	 * related SftPerfilCredencials from storage. If this SftPerfil is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SftPerfilCredencial[]
	 * @throws     PropelException
	 */
	public function getSftPerfilCredencials($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftPerfilCredencials === null) {
			if ($this->isNew()) {
			   $this->collSftPerfilCredencials = array();
			} else {

				$criteria->add(SftPerfilCredencialPeer::ID_PERFIL, $this->id);

				SftPerfilCredencialPeer::addSelectColumns($criteria);
				$this->collSftPerfilCredencials = SftPerfilCredencialPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SftPerfilCredencialPeer::ID_PERFIL, $this->id);

				SftPerfilCredencialPeer::addSelectColumns($criteria);
				if (!isset($this->lastSftPerfilCredencialCriteria) || !$this->lastSftPerfilCredencialCriteria->equals($criteria)) {
					$this->collSftPerfilCredencials = SftPerfilCredencialPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSftPerfilCredencialCriteria = $criteria;
		return $this->collSftPerfilCredencials;
	}

	/**
	 * Returns the number of related SftPerfilCredencial objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SftPerfilCredencial objects.
	 * @throws     PropelException
	 */
	public function countSftPerfilCredencials(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSftPerfilCredencials === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SftPerfilCredencialPeer::ID_PERFIL, $this->id);

				$count = SftPerfilCredencialPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SftPerfilCredencialPeer::ID_PERFIL, $this->id);

				if (!isset($this->lastSftPerfilCredencialCriteria) || !$this->lastSftPerfilCredencialCriteria->equals($criteria)) {
					$count = SftPerfilCredencialPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSftPerfilCredencials);
				}
			} else {
				$count = count($this->collSftPerfilCredencials);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SftPerfilCredencial object to this object
	 * through the SftPerfilCredencial foreign key attribute.
	 *
	 * @param      SftPerfilCredencial $l SftPerfilCredencial
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSftPerfilCredencial(SftPerfilCredencial $l)
	{
		if ($this->collSftPerfilCredencials === null) {
			$this->initSftPerfilCredencials();
		}
		if (!in_array($l, $this->collSftPerfilCredencials, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSftPerfilCredencials, $l);
			$l->setSftPerfil($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPerfil is new, it will return
	 * an empty collection; or if this SftPerfil has previously
	 * been saved, it will retrieve related SftPerfilCredencials from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPerfil.
	 */
	public function getSftPerfilCredencialsJoinSftCredencial($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftPerfilCredencials === null) {
			if ($this->isNew()) {
				$this->collSftPerfilCredencials = array();
			} else {

				$criteria->add(SftPerfilCredencialPeer::ID_PERFIL, $this->id);

				$this->collSftPerfilCredencials = SftPerfilCredencialPeer::doSelectJoinSftCredencial($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftPerfilCredencialPeer::ID_PERFIL, $this->id);

			if (!isset($this->lastSftPerfilCredencialCriteria) || !$this->lastSftPerfilCredencialCriteria->equals($criteria)) {
				$this->collSftPerfilCredencials = SftPerfilCredencialPeer::doSelectJoinSftCredencial($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftPerfilCredencialCriteria = $criteria;

		return $this->collSftPerfilCredencials;
	}

	/**
	 * Clears out the collSftPerfilI18ns collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSftPerfilI18ns()
	 */
	public function clearSftPerfilI18ns()
	{
		$this->collSftPerfilI18ns = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSftPerfilI18ns collection (array).
	 *
	 * By default this just sets the collSftPerfilI18ns collection to an empty array (like clearcollSftPerfilI18ns());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSftPerfilI18ns()
	{
		$this->collSftPerfilI18ns = array();
	}

	/**
	 * Gets an array of SftPerfilI18n objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SftPerfil has previously been saved, it will retrieve
	 * related SftPerfilI18ns from storage. If this SftPerfil is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SftPerfilI18n[]
	 * @throws     PropelException
	 */
	public function getSftPerfilI18ns($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftPerfilI18ns === null) {
			if ($this->isNew()) {
			   $this->collSftPerfilI18ns = array();
			} else {

				$criteria->add(SftPerfilI18nPeer::ID, $this->id);

				SftPerfilI18nPeer::addSelectColumns($criteria);
				$this->collSftPerfilI18ns = SftPerfilI18nPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SftPerfilI18nPeer::ID, $this->id);

				SftPerfilI18nPeer::addSelectColumns($criteria);
				if (!isset($this->lastSftPerfilI18nCriteria) || !$this->lastSftPerfilI18nCriteria->equals($criteria)) {
					$this->collSftPerfilI18ns = SftPerfilI18nPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSftPerfilI18nCriteria = $criteria;
		return $this->collSftPerfilI18ns;
	}

	/**
	 * Returns the number of related SftPerfilI18n objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SftPerfilI18n objects.
	 * @throws     PropelException
	 */
	public function countSftPerfilI18ns(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPerfilPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSftPerfilI18ns === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SftPerfilI18nPeer::ID, $this->id);

				$count = SftPerfilI18nPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SftPerfilI18nPeer::ID, $this->id);

				if (!isset($this->lastSftPerfilI18nCriteria) || !$this->lastSftPerfilI18nCriteria->equals($criteria)) {
					$count = SftPerfilI18nPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSftPerfilI18ns);
				}
			} else {
				$count = count($this->collSftPerfilI18ns);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SftPerfilI18n object to this object
	 * through the SftPerfilI18n foreign key attribute.
	 *
	 * @param      SftPerfilI18n $l SftPerfilI18n
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSftPerfilI18n(SftPerfilI18n $l)
	{
		if ($this->collSftPerfilI18ns === null) {
			$this->initSftPerfilI18ns();
		}
		if (!in_array($l, $this->collSftPerfilI18ns, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSftPerfilI18ns, $l);
			$l->setSftPerfil($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collSftAccesos) {
				foreach ((array) $this->collSftAccesos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSftConfPersonals) {
				foreach ((array) $this->collSftConfPersonals as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSftPerfilCredencials) {
				foreach ((array) $this->collSftPerfilCredencials as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSftPerfilI18ns) {
				foreach ((array) $this->collSftPerfilI18ns as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collSftAccesos = null;
		$this->collSftConfPersonals = null;
		$this->collSftPerfilCredencials = null;
		$this->collSftPerfilI18ns = null;
			$this->aSftUo = null;
			$this->aSftAmbitoTipo = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSftPerfil:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSftPerfil::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

	// symfony_i18n behavior
	
	/**
	 * Returns the culture.
	 *
	 * @return string The culture
	 */
	public function getCulture()
	{
	  return $this->culture;
	}
	
	/**
	 * Sets the culture.
	 *
	 * @param string  The culture to set
	 *
	 * @return SftPerfil
	 */
	public function setCulture($culture)
	{
	  $this->culture = $culture;
	  return $this;
	}
	
	/**
	 * Returns the "nombre" value from the current {@link SftPerfilI18n}.
	 */
	public function getNombre($culture = null)
	{
	  return $this->getCurrentSftPerfilI18n($culture)->getNombre();
	}
	
	/**
	 * Sets the "nombre" value of the current {@link SftPerfilI18n}.
	 *
	 * @return SftPerfil
	 */
	public function setNombre($value, $culture = null)
	{
	  $this->getCurrentSftPerfilI18n($culture)->setNombre($value);
	  return $this;
	}
	
	/**
	 * Returns the "descripcion" value from the current {@link SftPerfilI18n}.
	 */
	public function getDescripcion($culture = null)
	{
	  return $this->getCurrentSftPerfilI18n($culture)->getDescripcion();
	}
	
	/**
	 * Sets the "descripcion" value of the current {@link SftPerfilI18n}.
	 *
	 * @return SftPerfil
	 */
	public function setDescripcion($value, $culture = null)
	{
	  $this->getCurrentSftPerfilI18n($culture)->setDescripcion($value);
	  return $this;
	}
	
	/**
	 * Returns the "abreviatura" value from the current {@link SftPerfilI18n}.
	 */
	public function getAbreviatura($culture = null)
	{
	  return $this->getCurrentSftPerfilI18n($culture)->getAbreviatura();
	}
	
	/**
	 * Sets the "abreviatura" value of the current {@link SftPerfilI18n}.
	 *
	 * @return SftPerfil
	 */
	public function setAbreviatura($value, $culture = null)
	{
	  $this->getCurrentSftPerfilI18n($culture)->setAbreviatura($value);
	  return $this;
	}
	
	/**
	 * Returns the current translation.
	 *
	 * @return SftPerfilI18n
	 */
	public function getCurrentSftPerfilI18n($culture = null)
	{
	  if (null === $culture)
	  {
	    $culture = null === $this->culture ? sfPropel::getDefaultCulture() : $this->culture;
	  }
	
	  if (!isset($this->current_i18n[$culture]))
	  {
	    $object = $this->isNew() ? null : SftPerfilI18nPeer::retrieveByPK($this->getPrimaryKey(), $culture);
	    if ($object)
	    {
	      $this->setSftPerfilI18nForCulture($object, $culture);
	    }
	    else
	    {
	      $this->setSftPerfilI18nForCulture(new SftPerfilI18n(), $culture);
	      $this->current_i18n[$culture]->setIdCultura($culture);
	    }
	  }
	
	  return $this->current_i18n[$culture];
	}
	
	/**
	 * Sets the translation object for a culture.
	 */
	public function setSftPerfilI18nForCulture(SftPerfilI18n $object, $culture)
	{
	  $this->current_i18n[$culture] = $object;
	  $this->addSftPerfilI18n($object);
	}

} // BaseSftPerfil
