<?php

/**
 * Base class that represents a row from the 'sft_direcciones' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:09 2012
 *
 * @package    plugins.sftGuardPlugin.lib.model.om
 */
abstract class BaseSftDireccion extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SftDireccionPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the id_tipodireccion field.
	 * @var        int
	 */
	protected $id_tipodireccion;

	/**
	 * The value for the tipovia field.
	 * @var        string
	 */
	protected $tipovia;

	/**
	 * The value for the domicilio field.
	 * @var        string
	 */
	protected $domicilio;

	/**
	 * The value for the numero field.
	 * @var        string
	 */
	protected $numero;

	/**
	 * The value for the escalera field.
	 * @var        string
	 */
	protected $escalera;

	/**
	 * The value for the piso field.
	 * @var        string
	 */
	protected $piso;

	/**
	 * The value for the letra field.
	 * @var        string
	 */
	protected $letra;

	/**
	 * The value for the pais field.
	 * @var        string
	 */
	protected $pais;

	/**
	 * The value for the provincia field.
	 * @var        string
	 */
	protected $provincia;

	/**
	 * The value for the municipio field.
	 * @var        string
	 */
	protected $municipio;

	/**
	 * The value for the cp field.
	 * @var        string
	 */
	protected $cp;

	/**
	 * The value for the id_usuario field.
	 * @var        int
	 */
	protected $id_usuario;

	/**
	 * @var        SftTipoDireccion
	 */
	protected $aSftTipoDireccion;

	/**
	 * @var        SftUsuario
	 */
	protected $aSftUsuario;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SftDireccionPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [id_tipodireccion] column value.
	 * 
	 * @return     int
	 */
	public function getIdTipodireccion()
	{
		return $this->id_tipodireccion;
	}

	/**
	 * Get the [tipovia] column value.
	 * 
	 * @return     string
	 */
	public function getTipovia()
	{
		return $this->tipovia;
	}

	/**
	 * Get the [domicilio] column value.
	 * 
	 * @return     string
	 */
	public function getDomicilio()
	{
		return $this->domicilio;
	}

	/**
	 * Get the [numero] column value.
	 * 
	 * @return     string
	 */
	public function getNumero()
	{
		return $this->numero;
	}

	/**
	 * Get the [escalera] column value.
	 * 
	 * @return     string
	 */
	public function getEscalera()
	{
		return $this->escalera;
	}

	/**
	 * Get the [piso] column value.
	 * 
	 * @return     string
	 */
	public function getPiso()
	{
		return $this->piso;
	}

	/**
	 * Get the [letra] column value.
	 * 
	 * @return     string
	 */
	public function getLetra()
	{
		return $this->letra;
	}

	/**
	 * Get the [pais] column value.
	 * 
	 * @return     string
	 */
	public function getPais()
	{
		return $this->pais;
	}

	/**
	 * Get the [provincia] column value.
	 * 
	 * @return     string
	 */
	public function getProvincia()
	{
		return $this->provincia;
	}

	/**
	 * Get the [municipio] column value.
	 * 
	 * @return     string
	 */
	public function getMunicipio()
	{
		return $this->municipio;
	}

	/**
	 * Get the [cp] column value.
	 * 
	 * @return     string
	 */
	public function getCp()
	{
		return $this->cp;
	}

	/**
	 * Get the [id_usuario] column value.
	 * 
	 * @return     int
	 */
	public function getIdUsuario()
	{
		return $this->id_usuario;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SftDireccionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [id_tipodireccion] column.
	 * 
	 * @param      int $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setIdTipodireccion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tipodireccion !== $v) {
			$this->id_tipodireccion = $v;
			$this->modifiedColumns[] = SftDireccionPeer::ID_TIPODIRECCION;
		}

		if ($this->aSftTipoDireccion !== null && $this->aSftTipoDireccion->getId() !== $v) {
			$this->aSftTipoDireccion = null;
		}

		return $this;
	} // setIdTipodireccion()

	/**
	 * Set the value of [tipovia] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setTipovia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tipovia !== $v) {
			$this->tipovia = $v;
			$this->modifiedColumns[] = SftDireccionPeer::TIPOVIA;
		}

		return $this;
	} // setTipovia()

	/**
	 * Set the value of [domicilio] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setDomicilio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->domicilio !== $v) {
			$this->domicilio = $v;
			$this->modifiedColumns[] = SftDireccionPeer::DOMICILIO;
		}

		return $this;
	} // setDomicilio()

	/**
	 * Set the value of [numero] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setNumero($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->numero !== $v) {
			$this->numero = $v;
			$this->modifiedColumns[] = SftDireccionPeer::NUMERO;
		}

		return $this;
	} // setNumero()

	/**
	 * Set the value of [escalera] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setEscalera($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->escalera !== $v) {
			$this->escalera = $v;
			$this->modifiedColumns[] = SftDireccionPeer::ESCALERA;
		}

		return $this;
	} // setEscalera()

	/**
	 * Set the value of [piso] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setPiso($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->piso !== $v) {
			$this->piso = $v;
			$this->modifiedColumns[] = SftDireccionPeer::PISO;
		}

		return $this;
	} // setPiso()

	/**
	 * Set the value of [letra] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setLetra($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->letra !== $v) {
			$this->letra = $v;
			$this->modifiedColumns[] = SftDireccionPeer::LETRA;
		}

		return $this;
	} // setLetra()

	/**
	 * Set the value of [pais] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setPais($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pais !== $v) {
			$this->pais = $v;
			$this->modifiedColumns[] = SftDireccionPeer::PAIS;
		}

		return $this;
	} // setPais()

	/**
	 * Set the value of [provincia] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setProvincia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->provincia !== $v) {
			$this->provincia = $v;
			$this->modifiedColumns[] = SftDireccionPeer::PROVINCIA;
		}

		return $this;
	} // setProvincia()

	/**
	 * Set the value of [municipio] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setMunicipio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->municipio !== $v) {
			$this->municipio = $v;
			$this->modifiedColumns[] = SftDireccionPeer::MUNICIPIO;
		}

		return $this;
	} // setMunicipio()

	/**
	 * Set the value of [cp] column.
	 * 
	 * @param      string $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setCp($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cp !== $v) {
			$this->cp = $v;
			$this->modifiedColumns[] = SftDireccionPeer::CP;
		}

		return $this;
	} // setCp()

	/**
	 * Set the value of [id_usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     SftDireccion The current object (for fluent API support)
	 */
	public function setIdUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_usuario !== $v) {
			$this->id_usuario = $v;
			$this->modifiedColumns[] = SftDireccionPeer::ID_USUARIO;
		}

		if ($this->aSftUsuario !== null && $this->aSftUsuario->getId() !== $v) {
			$this->aSftUsuario = null;
		}

		return $this;
	} // setIdUsuario()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_tipodireccion = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->tipovia = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->domicilio = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->numero = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->escalera = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->piso = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->letra = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->pais = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->provincia = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->municipio = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->cp = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->id_usuario = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = SftDireccionPeer::NUM_COLUMNS - SftDireccionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating SftDireccion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSftTipoDireccion !== null && $this->id_tipodireccion !== $this->aSftTipoDireccion->getId()) {
			$this->aSftTipoDireccion = null;
		}
		if ($this->aSftUsuario !== null && $this->id_usuario !== $this->aSftUsuario->getId()) {
			$this->aSftUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftDireccionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SftDireccionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSftTipoDireccion = null;
			$this->aSftUsuario = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftDireccionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSftDireccion:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				SftDireccionPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSftDireccion:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftDireccionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSftDireccion:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSftDireccion:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SftDireccionPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSftTipoDireccion !== null) {
				if ($this->aSftTipoDireccion->isModified() || $this->aSftTipoDireccion->isNew()) {
					$affectedRows += $this->aSftTipoDireccion->save($con);
				}
				$this->setSftTipoDireccion($this->aSftTipoDireccion);
			}

			if ($this->aSftUsuario !== null) {
				if ($this->aSftUsuario->isModified() || $this->aSftUsuario->isNew()) {
					$affectedRows += $this->aSftUsuario->save($con);
				}
				$this->setSftUsuario($this->aSftUsuario);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SftDireccionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SftDireccionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SftDireccionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSftTipoDireccion !== null) {
				if (!$this->aSftTipoDireccion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSftTipoDireccion->getValidationFailures());
				}
			}

			if ($this->aSftUsuario !== null) {
				if (!$this->aSftUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSftUsuario->getValidationFailures());
				}
			}


			if (($retval = SftDireccionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SftDireccionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getIdTipodireccion();
				break;
			case 2:
				return $this->getTipovia();
				break;
			case 3:
				return $this->getDomicilio();
				break;
			case 4:
				return $this->getNumero();
				break;
			case 5:
				return $this->getEscalera();
				break;
			case 6:
				return $this->getPiso();
				break;
			case 7:
				return $this->getLetra();
				break;
			case 8:
				return $this->getPais();
				break;
			case 9:
				return $this->getProvincia();
				break;
			case 10:
				return $this->getMunicipio();
				break;
			case 11:
				return $this->getCp();
				break;
			case 12:
				return $this->getIdUsuario();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SftDireccionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getIdTipodireccion(),
			$keys[2] => $this->getTipovia(),
			$keys[3] => $this->getDomicilio(),
			$keys[4] => $this->getNumero(),
			$keys[5] => $this->getEscalera(),
			$keys[6] => $this->getPiso(),
			$keys[7] => $this->getLetra(),
			$keys[8] => $this->getPais(),
			$keys[9] => $this->getProvincia(),
			$keys[10] => $this->getMunicipio(),
			$keys[11] => $this->getCp(),
			$keys[12] => $this->getIdUsuario(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SftDireccionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setIdTipodireccion($value);
				break;
			case 2:
				$this->setTipovia($value);
				break;
			case 3:
				$this->setDomicilio($value);
				break;
			case 4:
				$this->setNumero($value);
				break;
			case 5:
				$this->setEscalera($value);
				break;
			case 6:
				$this->setPiso($value);
				break;
			case 7:
				$this->setLetra($value);
				break;
			case 8:
				$this->setPais($value);
				break;
			case 9:
				$this->setProvincia($value);
				break;
			case 10:
				$this->setMunicipio($value);
				break;
			case 11:
				$this->setCp($value);
				break;
			case 12:
				$this->setIdUsuario($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SftDireccionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdTipodireccion($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTipovia($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDomicilio($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNumero($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEscalera($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPiso($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setLetra($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPais($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setProvincia($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setMunicipio($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCp($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setIdUsuario($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SftDireccionPeer::DATABASE_NAME);

		if ($this->isColumnModified(SftDireccionPeer::ID)) $criteria->add(SftDireccionPeer::ID, $this->id);
		if ($this->isColumnModified(SftDireccionPeer::ID_TIPODIRECCION)) $criteria->add(SftDireccionPeer::ID_TIPODIRECCION, $this->id_tipodireccion);
		if ($this->isColumnModified(SftDireccionPeer::TIPOVIA)) $criteria->add(SftDireccionPeer::TIPOVIA, $this->tipovia);
		if ($this->isColumnModified(SftDireccionPeer::DOMICILIO)) $criteria->add(SftDireccionPeer::DOMICILIO, $this->domicilio);
		if ($this->isColumnModified(SftDireccionPeer::NUMERO)) $criteria->add(SftDireccionPeer::NUMERO, $this->numero);
		if ($this->isColumnModified(SftDireccionPeer::ESCALERA)) $criteria->add(SftDireccionPeer::ESCALERA, $this->escalera);
		if ($this->isColumnModified(SftDireccionPeer::PISO)) $criteria->add(SftDireccionPeer::PISO, $this->piso);
		if ($this->isColumnModified(SftDireccionPeer::LETRA)) $criteria->add(SftDireccionPeer::LETRA, $this->letra);
		if ($this->isColumnModified(SftDireccionPeer::PAIS)) $criteria->add(SftDireccionPeer::PAIS, $this->pais);
		if ($this->isColumnModified(SftDireccionPeer::PROVINCIA)) $criteria->add(SftDireccionPeer::PROVINCIA, $this->provincia);
		if ($this->isColumnModified(SftDireccionPeer::MUNICIPIO)) $criteria->add(SftDireccionPeer::MUNICIPIO, $this->municipio);
		if ($this->isColumnModified(SftDireccionPeer::CP)) $criteria->add(SftDireccionPeer::CP, $this->cp);
		if ($this->isColumnModified(SftDireccionPeer::ID_USUARIO)) $criteria->add(SftDireccionPeer::ID_USUARIO, $this->id_usuario);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SftDireccionPeer::DATABASE_NAME);

		$criteria->add(SftDireccionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of SftDireccion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdTipodireccion($this->id_tipodireccion);

		$copyObj->setTipovia($this->tipovia);

		$copyObj->setDomicilio($this->domicilio);

		$copyObj->setNumero($this->numero);

		$copyObj->setEscalera($this->escalera);

		$copyObj->setPiso($this->piso);

		$copyObj->setLetra($this->letra);

		$copyObj->setPais($this->pais);

		$copyObj->setProvincia($this->provincia);

		$copyObj->setMunicipio($this->municipio);

		$copyObj->setCp($this->cp);

		$copyObj->setIdUsuario($this->id_usuario);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     SftDireccion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SftDireccionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SftDireccionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a SftTipoDireccion object.
	 *
	 * @param      SftTipoDireccion $v
	 * @return     SftDireccion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSftTipoDireccion(SftTipoDireccion $v = null)
	{
		if ($v === null) {
			$this->setIdTipodireccion(NULL);
		} else {
			$this->setIdTipodireccion($v->getId());
		}

		$this->aSftTipoDireccion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SftTipoDireccion object, it will not be re-added.
		if ($v !== null) {
			$v->addSftDireccion($this);
		}

		return $this;
	}


	/**
	 * Get the associated SftTipoDireccion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SftTipoDireccion The associated SftTipoDireccion object.
	 * @throws     PropelException
	 */
	public function getSftTipoDireccion(PropelPDO $con = null)
	{
		if ($this->aSftTipoDireccion === null && ($this->id_tipodireccion !== null)) {
			$this->aSftTipoDireccion = SftTipoDireccionPeer::retrieveByPk($this->id_tipodireccion);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSftTipoDireccion->addSftDireccions($this);
			 */
		}
		return $this->aSftTipoDireccion;
	}

	/**
	 * Declares an association between this object and a SftUsuario object.
	 *
	 * @param      SftUsuario $v
	 * @return     SftDireccion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSftUsuario(SftUsuario $v = null)
	{
		if ($v === null) {
			$this->setIdUsuario(NULL);
		} else {
			$this->setIdUsuario($v->getId());
		}

		$this->aSftUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SftUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addSftDireccion($this);
		}

		return $this;
	}


	/**
	 * Get the associated SftUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SftUsuario The associated SftUsuario object.
	 * @throws     PropelException
	 */
	public function getSftUsuario(PropelPDO $con = null)
	{
		if ($this->aSftUsuario === null && ($this->id_usuario !== null)) {
			$this->aSftUsuario = SftUsuarioPeer::retrieveByPk($this->id_usuario);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSftUsuario->addSftDireccions($this);
			 */
		}
		return $this->aSftUsuario;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aSftTipoDireccion = null;
			$this->aSftUsuario = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSftDireccion:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSftDireccion::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseSftDireccion
