<?php

/**
 * Base class that represents a row from the 'sft_personas' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 21:13:12 2012
 *
 * @package    plugins.sftGuardPlugin.lib.model.om
 */
abstract class BaseSftPersona extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        SftPersonaPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the apellido1 field.
	 * @var        string
	 */
	protected $apellido1;

	/**
	 * The value for the apellido2 field.
	 * @var        string
	 */
	protected $apellido2;

	/**
	 * The value for the id_tipodocidentificacion field.
	 * @var        int
	 */
	protected $id_tipodocidentificacion;

	/**
	 * The value for the docidentificacion field.
	 * @var        string
	 */
	protected $docidentificacion;

	/**
	 * The value for the id_paisdocidentificacion field.
	 * @var        int
	 */
	protected $id_paisdocidentificacion;

	/**
	 * The value for the sexo field.
	 * @var        string
	 */
	protected $sexo;

	/**
	 * The value for the fechanacimiento field.
	 * @var        string
	 */
	protected $fechanacimiento;

	/**
	 * The value for the observaciones field.
	 * @var        string
	 */
	protected $observaciones;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the profesion field.
	 * @var        string
	 */
	protected $profesion;

	/**
	 * @var        SftTipoDocIdentificacion
	 */
	protected $aSftTipoDocIdentificacion;

	/**
	 * @var        GenPais
	 */
	protected $aGenPais;

	/**
	 * @var        array SftOrganismo[] Collection to store aggregation of SftOrganismo objects.
	 */
	protected $collSftOrganismos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSftOrganismos.
	 */
	private $lastSftOrganismoCriteria = null;

	/**
	 * @var        array SftUsuario[] Collection to store aggregation of SftUsuario objects.
	 */
	protected $collSftUsuarios;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSftUsuarios.
	 */
	private $lastSftUsuarioCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'SftPersonaPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [apellido1] column value.
	 * 
	 * @return     string
	 */
	public function getApellido1()
	{
		return $this->apellido1;
	}

	/**
	 * Get the [apellido2] column value.
	 * 
	 * @return     string
	 */
	public function getApellido2()
	{
		return $this->apellido2;
	}

	/**
	 * Get the [id_tipodocidentificacion] column value.
	 * 
	 * @return     int
	 */
	public function getIdTipodocidentificacion()
	{
		return $this->id_tipodocidentificacion;
	}

	/**
	 * Get the [docidentificacion] column value.
	 * 
	 * @return     string
	 */
	public function getDocidentificacion()
	{
		return $this->docidentificacion;
	}

	/**
	 * Get the [id_paisdocidentificacion] column value.
	 * 
	 * @return     int
	 */
	public function getIdPaisdocidentificacion()
	{
		return $this->id_paisdocidentificacion;
	}

	/**
	 * Get the [sexo] column value.
	 * 
	 * @return     string
	 */
	public function getSexo()
	{
		return $this->sexo;
	}

	/**
	 * Get the [optionally formatted] temporal [fechanacimiento] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechanacimiento($format = 'Y-m-d')
	{
		if ($this->fechanacimiento === null) {
			return null;
		}


		if ($this->fechanacimiento === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fechanacimiento);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fechanacimiento, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [observaciones] column value.
	 * 
	 * @return     string
	 */
	public function getObservaciones()
	{
		return $this->observaciones;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [profesion] column value.
	 * 
	 * @return     string
	 */
	public function getProfesion()
	{
		return $this->profesion;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = SftPersonaPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = SftPersonaPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [apellido1] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setApellido1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->apellido1 !== $v) {
			$this->apellido1 = $v;
			$this->modifiedColumns[] = SftPersonaPeer::APELLIDO1;
		}

		return $this;
	} // setApellido1()

	/**
	 * Set the value of [apellido2] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setApellido2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->apellido2 !== $v) {
			$this->apellido2 = $v;
			$this->modifiedColumns[] = SftPersonaPeer::APELLIDO2;
		}

		return $this;
	} // setApellido2()

	/**
	 * Set the value of [id_tipodocidentificacion] column.
	 * 
	 * @param      int $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setIdTipodocidentificacion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_tipodocidentificacion !== $v) {
			$this->id_tipodocidentificacion = $v;
			$this->modifiedColumns[] = SftPersonaPeer::ID_TIPODOCIDENTIFICACION;
		}

		if ($this->aSftTipoDocIdentificacion !== null && $this->aSftTipoDocIdentificacion->getId() !== $v) {
			$this->aSftTipoDocIdentificacion = null;
		}

		return $this;
	} // setIdTipodocidentificacion()

	/**
	 * Set the value of [docidentificacion] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setDocidentificacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->docidentificacion !== $v) {
			$this->docidentificacion = $v;
			$this->modifiedColumns[] = SftPersonaPeer::DOCIDENTIFICACION;
		}

		return $this;
	} // setDocidentificacion()

	/**
	 * Set the value of [id_paisdocidentificacion] column.
	 * 
	 * @param      int $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setIdPaisdocidentificacion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_paisdocidentificacion !== $v) {
			$this->id_paisdocidentificacion = $v;
			$this->modifiedColumns[] = SftPersonaPeer::ID_PAISDOCIDENTIFICACION;
		}

		if ($this->aGenPais !== null && $this->aGenPais->getId() !== $v) {
			$this->aGenPais = null;
		}

		return $this;
	} // setIdPaisdocidentificacion()

	/**
	 * Set the value of [sexo] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setSexo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->sexo !== $v) {
			$this->sexo = $v;
			$this->modifiedColumns[] = SftPersonaPeer::SEXO;
		}

		return $this;
	} // setSexo()

	/**
	 * Sets the value of [fechanacimiento] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setFechanacimiento($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fechanacimiento !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fechanacimiento !== null && $tmpDt = new DateTime($this->fechanacimiento)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fechanacimiento = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = SftPersonaPeer::FECHANACIMIENTO;
			}
		} // if either are not null

		return $this;
	} // setFechanacimiento()

	/**
	 * Set the value of [observaciones] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setObservaciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->observaciones !== $v) {
			$this->observaciones = $v;
			$this->modifiedColumns[] = SftPersonaPeer::OBSERVACIONES;
		}

		return $this;
	} // setObservaciones()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SftPersonaPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = SftPersonaPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [profesion] column.
	 * 
	 * @param      string $v new value
	 * @return     SftPersona The current object (for fluent API support)
	 */
	public function setProfesion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profesion !== $v) {
			$this->profesion = $v;
			$this->modifiedColumns[] = SftPersonaPeer::PROFESION;
		}

		return $this;
	} // setProfesion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->apellido1 = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->apellido2 = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->id_tipodocidentificacion = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->docidentificacion = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->id_paisdocidentificacion = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->sexo = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->fechanacimiento = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->observaciones = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->created_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->updated_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->profesion = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = SftPersonaPeer::NUM_COLUMNS - SftPersonaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating SftPersona object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSftTipoDocIdentificacion !== null && $this->id_tipodocidentificacion !== $this->aSftTipoDocIdentificacion->getId()) {
			$this->aSftTipoDocIdentificacion = null;
		}
		if ($this->aGenPais !== null && $this->id_paisdocidentificacion !== $this->aGenPais->getId()) {
			$this->aGenPais = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftPersonaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = SftPersonaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSftTipoDocIdentificacion = null;
			$this->aGenPais = null;
			$this->collSftOrganismos = null;
			$this->lastSftOrganismoCriteria = null;

			$this->collSftUsuarios = null;
			$this->lastSftUsuarioCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftPersonaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSftPersona:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				SftPersonaPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSftPersona:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(SftPersonaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseSftPersona:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(SftPersonaPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(SftPersonaPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseSftPersona:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				SftPersonaPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSftTipoDocIdentificacion !== null) {
				if ($this->aSftTipoDocIdentificacion->isModified() || $this->aSftTipoDocIdentificacion->isNew()) {
					$affectedRows += $this->aSftTipoDocIdentificacion->save($con);
				}
				$this->setSftTipoDocIdentificacion($this->aSftTipoDocIdentificacion);
			}

			if ($this->aGenPais !== null) {
				if ($this->aGenPais->isModified() || $this->aGenPais->isNew()) {
					$affectedRows += $this->aGenPais->save($con);
				}
				$this->setGenPais($this->aGenPais);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = SftPersonaPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = SftPersonaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += SftPersonaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collSftOrganismos !== null) {
				foreach ($this->collSftOrganismos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collSftUsuarios !== null) {
				foreach ($this->collSftUsuarios as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSftTipoDocIdentificacion !== null) {
				if (!$this->aSftTipoDocIdentificacion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSftTipoDocIdentificacion->getValidationFailures());
				}
			}

			if ($this->aGenPais !== null) {
				if (!$this->aGenPais->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aGenPais->getValidationFailures());
				}
			}


			if (($retval = SftPersonaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collSftOrganismos !== null) {
					foreach ($this->collSftOrganismos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collSftUsuarios !== null) {
					foreach ($this->collSftUsuarios as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SftPersonaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNombre();
				break;
			case 2:
				return $this->getApellido1();
				break;
			case 3:
				return $this->getApellido2();
				break;
			case 4:
				return $this->getIdTipodocidentificacion();
				break;
			case 5:
				return $this->getDocidentificacion();
				break;
			case 6:
				return $this->getIdPaisdocidentificacion();
				break;
			case 7:
				return $this->getSexo();
				break;
			case 8:
				return $this->getFechanacimiento();
				break;
			case 9:
				return $this->getObservaciones();
				break;
			case 10:
				return $this->getCreatedAt();
				break;
			case 11:
				return $this->getUpdatedAt();
				break;
			case 12:
				return $this->getProfesion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = SftPersonaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNombre(),
			$keys[2] => $this->getApellido1(),
			$keys[3] => $this->getApellido2(),
			$keys[4] => $this->getIdTipodocidentificacion(),
			$keys[5] => $this->getDocidentificacion(),
			$keys[6] => $this->getIdPaisdocidentificacion(),
			$keys[7] => $this->getSexo(),
			$keys[8] => $this->getFechanacimiento(),
			$keys[9] => $this->getObservaciones(),
			$keys[10] => $this->getCreatedAt(),
			$keys[11] => $this->getUpdatedAt(),
			$keys[12] => $this->getProfesion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = SftPersonaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNombre($value);
				break;
			case 2:
				$this->setApellido1($value);
				break;
			case 3:
				$this->setApellido2($value);
				break;
			case 4:
				$this->setIdTipodocidentificacion($value);
				break;
			case 5:
				$this->setDocidentificacion($value);
				break;
			case 6:
				$this->setIdPaisdocidentificacion($value);
				break;
			case 7:
				$this->setSexo($value);
				break;
			case 8:
				$this->setFechanacimiento($value);
				break;
			case 9:
				$this->setObservaciones($value);
				break;
			case 10:
				$this->setCreatedAt($value);
				break;
			case 11:
				$this->setUpdatedAt($value);
				break;
			case 12:
				$this->setProfesion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = SftPersonaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNombre($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setApellido1($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setApellido2($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setIdTipodocidentificacion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDocidentificacion($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setIdPaisdocidentificacion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setSexo($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFechanacimiento($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setObservaciones($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCreatedAt($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUpdatedAt($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setProfesion($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);

		if ($this->isColumnModified(SftPersonaPeer::ID)) $criteria->add(SftPersonaPeer::ID, $this->id);
		if ($this->isColumnModified(SftPersonaPeer::NOMBRE)) $criteria->add(SftPersonaPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(SftPersonaPeer::APELLIDO1)) $criteria->add(SftPersonaPeer::APELLIDO1, $this->apellido1);
		if ($this->isColumnModified(SftPersonaPeer::APELLIDO2)) $criteria->add(SftPersonaPeer::APELLIDO2, $this->apellido2);
		if ($this->isColumnModified(SftPersonaPeer::ID_TIPODOCIDENTIFICACION)) $criteria->add(SftPersonaPeer::ID_TIPODOCIDENTIFICACION, $this->id_tipodocidentificacion);
		if ($this->isColumnModified(SftPersonaPeer::DOCIDENTIFICACION)) $criteria->add(SftPersonaPeer::DOCIDENTIFICACION, $this->docidentificacion);
		if ($this->isColumnModified(SftPersonaPeer::ID_PAISDOCIDENTIFICACION)) $criteria->add(SftPersonaPeer::ID_PAISDOCIDENTIFICACION, $this->id_paisdocidentificacion);
		if ($this->isColumnModified(SftPersonaPeer::SEXO)) $criteria->add(SftPersonaPeer::SEXO, $this->sexo);
		if ($this->isColumnModified(SftPersonaPeer::FECHANACIMIENTO)) $criteria->add(SftPersonaPeer::FECHANACIMIENTO, $this->fechanacimiento);
		if ($this->isColumnModified(SftPersonaPeer::OBSERVACIONES)) $criteria->add(SftPersonaPeer::OBSERVACIONES, $this->observaciones);
		if ($this->isColumnModified(SftPersonaPeer::CREATED_AT)) $criteria->add(SftPersonaPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(SftPersonaPeer::UPDATED_AT)) $criteria->add(SftPersonaPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(SftPersonaPeer::PROFESION)) $criteria->add(SftPersonaPeer::PROFESION, $this->profesion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);

		$criteria->add(SftPersonaPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of SftPersona (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNombre($this->nombre);

		$copyObj->setApellido1($this->apellido1);

		$copyObj->setApellido2($this->apellido2);

		$copyObj->setIdTipodocidentificacion($this->id_tipodocidentificacion);

		$copyObj->setDocidentificacion($this->docidentificacion);

		$copyObj->setIdPaisdocidentificacion($this->id_paisdocidentificacion);

		$copyObj->setSexo($this->sexo);

		$copyObj->setFechanacimiento($this->fechanacimiento);

		$copyObj->setObservaciones($this->observaciones);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setProfesion($this->profesion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getSftOrganismos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSftOrganismo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getSftUsuarios() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSftUsuario($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     SftPersona Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     SftPersonaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new SftPersonaPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a SftTipoDocIdentificacion object.
	 *
	 * @param      SftTipoDocIdentificacion $v
	 * @return     SftPersona The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSftTipoDocIdentificacion(SftTipoDocIdentificacion $v = null)
	{
		if ($v === null) {
			$this->setIdTipodocidentificacion(NULL);
		} else {
			$this->setIdTipodocidentificacion($v->getId());
		}

		$this->aSftTipoDocIdentificacion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SftTipoDocIdentificacion object, it will not be re-added.
		if ($v !== null) {
			$v->addSftPersona($this);
		}

		return $this;
	}


	/**
	 * Get the associated SftTipoDocIdentificacion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SftTipoDocIdentificacion The associated SftTipoDocIdentificacion object.
	 * @throws     PropelException
	 */
	public function getSftTipoDocIdentificacion(PropelPDO $con = null)
	{
		if ($this->aSftTipoDocIdentificacion === null && ($this->id_tipodocidentificacion !== null)) {
			$this->aSftTipoDocIdentificacion = SftTipoDocIdentificacionPeer::retrieveByPk($this->id_tipodocidentificacion);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSftTipoDocIdentificacion->addSftPersonas($this);
			 */
		}
		return $this->aSftTipoDocIdentificacion;
	}

	/**
	 * Declares an association between this object and a GenPais object.
	 *
	 * @param      GenPais $v
	 * @return     SftPersona The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setGenPais(GenPais $v = null)
	{
		if ($v === null) {
			$this->setIdPaisdocidentificacion(NULL);
		} else {
			$this->setIdPaisdocidentificacion($v->getId());
		}

		$this->aGenPais = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the GenPais object, it will not be re-added.
		if ($v !== null) {
			$v->addSftPersona($this);
		}

		return $this;
	}


	/**
	 * Get the associated GenPais object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     GenPais The associated GenPais object.
	 * @throws     PropelException
	 */
	public function getGenPais(PropelPDO $con = null)
	{
		if ($this->aGenPais === null && ($this->id_paisdocidentificacion !== null)) {
			$this->aGenPais = GenPaisPeer::retrieveByPk($this->id_paisdocidentificacion);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aGenPais->addSftPersonas($this);
			 */
		}
		return $this->aGenPais;
	}

	/**
	 * Clears out the collSftOrganismos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSftOrganismos()
	 */
	public function clearSftOrganismos()
	{
		$this->collSftOrganismos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSftOrganismos collection (array).
	 *
	 * By default this just sets the collSftOrganismos collection to an empty array (like clearcollSftOrganismos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSftOrganismos()
	{
		$this->collSftOrganismos = array();
	}

	/**
	 * Gets an array of SftOrganismo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SftPersona has previously been saved, it will retrieve
	 * related SftOrganismos from storage. If this SftPersona is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SftOrganismo[]
	 * @throws     PropelException
	 */
	public function getSftOrganismos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftOrganismos === null) {
			if ($this->isNew()) {
			   $this->collSftOrganismos = array();
			} else {

				$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

				SftOrganismoPeer::addSelectColumns($criteria);
				$this->collSftOrganismos = SftOrganismoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

				SftOrganismoPeer::addSelectColumns($criteria);
				if (!isset($this->lastSftOrganismoCriteria) || !$this->lastSftOrganismoCriteria->equals($criteria)) {
					$this->collSftOrganismos = SftOrganismoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSftOrganismoCriteria = $criteria;
		return $this->collSftOrganismos;
	}

	/**
	 * Returns the number of related SftOrganismo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SftOrganismo objects.
	 * @throws     PropelException
	 */
	public function countSftOrganismos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSftOrganismos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

				$count = SftOrganismoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

				if (!isset($this->lastSftOrganismoCriteria) || !$this->lastSftOrganismoCriteria->equals($criteria)) {
					$count = SftOrganismoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSftOrganismos);
				}
			} else {
				$count = count($this->collSftOrganismos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SftOrganismo object to this object
	 * through the SftOrganismo foreign key attribute.
	 *
	 * @param      SftOrganismo $l SftOrganismo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSftOrganismo(SftOrganismo $l)
	{
		if ($this->collSftOrganismos === null) {
			$this->initSftOrganismos();
		}
		if (!in_array($l, $this->collSftOrganismos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSftOrganismos, $l);
			$l->setSftPersona($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPersona is new, it will return
	 * an empty collection; or if this SftPersona has previously
	 * been saved, it will retrieve related SftOrganismos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPersona.
	 */
	public function getSftOrganismosJoinSftTipoOrganismo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftOrganismos === null) {
			if ($this->isNew()) {
				$this->collSftOrganismos = array();
			} else {

				$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

				$this->collSftOrganismos = SftOrganismoPeer::doSelectJoinSftTipoOrganismo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

			if (!isset($this->lastSftOrganismoCriteria) || !$this->lastSftOrganismoCriteria->equals($criteria)) {
				$this->collSftOrganismos = SftOrganismoPeer::doSelectJoinSftTipoOrganismo($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftOrganismoCriteria = $criteria;

		return $this->collSftOrganismos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPersona is new, it will return
	 * an empty collection; or if this SftPersona has previously
	 * been saved, it will retrieve related SftOrganismos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPersona.
	 */
	public function getSftOrganismosJoinSftOrganismoRelatedByIdDepende($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftOrganismos === null) {
			if ($this->isNew()) {
				$this->collSftOrganismos = array();
			} else {

				$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

				$this->collSftOrganismos = SftOrganismoPeer::doSelectJoinSftOrganismoRelatedByIdDepende($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

			if (!isset($this->lastSftOrganismoCriteria) || !$this->lastSftOrganismoCriteria->equals($criteria)) {
				$this->collSftOrganismos = SftOrganismoPeer::doSelectJoinSftOrganismoRelatedByIdDepende($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftOrganismoCriteria = $criteria;

		return $this->collSftOrganismos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPersona is new, it will return
	 * an empty collection; or if this SftPersona has previously
	 * been saved, it will retrieve related SftOrganismos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPersona.
	 */
	public function getSftOrganismosJoinGenPais($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftOrganismos === null) {
			if ($this->isNew()) {
				$this->collSftOrganismos = array();
			} else {

				$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

				$this->collSftOrganismos = SftOrganismoPeer::doSelectJoinGenPais($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftOrganismoPeer::ID_CONTACTO, $this->id);

			if (!isset($this->lastSftOrganismoCriteria) || !$this->lastSftOrganismoCriteria->equals($criteria)) {
				$this->collSftOrganismos = SftOrganismoPeer::doSelectJoinGenPais($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftOrganismoCriteria = $criteria;

		return $this->collSftOrganismos;
	}

	/**
	 * Clears out the collSftUsuarios collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSftUsuarios()
	 */
	public function clearSftUsuarios()
	{
		$this->collSftUsuarios = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSftUsuarios collection (array).
	 *
	 * By default this just sets the collSftUsuarios collection to an empty array (like clearcollSftUsuarios());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSftUsuarios()
	{
		$this->collSftUsuarios = array();
	}

	/**
	 * Gets an array of SftUsuario objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this SftPersona has previously been saved, it will retrieve
	 * related SftUsuarios from storage. If this SftPersona is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SftUsuario[]
	 * @throws     PropelException
	 */
	public function getSftUsuarios($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftUsuarios === null) {
			if ($this->isNew()) {
			   $this->collSftUsuarios = array();
			} else {

				$criteria->add(SftUsuarioPeer::ID_PERSONA, $this->id);

				SftUsuarioPeer::addSelectColumns($criteria);
				$this->collSftUsuarios = SftUsuarioPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SftUsuarioPeer::ID_PERSONA, $this->id);

				SftUsuarioPeer::addSelectColumns($criteria);
				if (!isset($this->lastSftUsuarioCriteria) || !$this->lastSftUsuarioCriteria->equals($criteria)) {
					$this->collSftUsuarios = SftUsuarioPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSftUsuarioCriteria = $criteria;
		return $this->collSftUsuarios;
	}

	/**
	 * Returns the number of related SftUsuario objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SftUsuario objects.
	 * @throws     PropelException
	 */
	public function countSftUsuarios(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSftUsuarios === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SftUsuarioPeer::ID_PERSONA, $this->id);

				$count = SftUsuarioPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SftUsuarioPeer::ID_PERSONA, $this->id);

				if (!isset($this->lastSftUsuarioCriteria) || !$this->lastSftUsuarioCriteria->equals($criteria)) {
					$count = SftUsuarioPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSftUsuarios);
				}
			} else {
				$count = count($this->collSftUsuarios);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SftUsuario object to this object
	 * through the SftUsuario foreign key attribute.
	 *
	 * @param      SftUsuario $l SftUsuario
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSftUsuario(SftUsuario $l)
	{
		if ($this->collSftUsuarios === null) {
			$this->initSftUsuarios();
		}
		if (!in_array($l, $this->collSftUsuarios, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSftUsuarios, $l);
			$l->setSftPersona($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this SftPersona is new, it will return
	 * an empty collection; or if this SftPersona has previously
	 * been saved, it will retrieve related SftUsuarios from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in SftPersona.
	 */
	public function getSftUsuariosJoinSftOrganismo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(SftPersonaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSftUsuarios === null) {
			if ($this->isNew()) {
				$this->collSftUsuarios = array();
			} else {

				$criteria->add(SftUsuarioPeer::ID_PERSONA, $this->id);

				$this->collSftUsuarios = SftUsuarioPeer::doSelectJoinSftOrganismo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SftUsuarioPeer::ID_PERSONA, $this->id);

			if (!isset($this->lastSftUsuarioCriteria) || !$this->lastSftUsuarioCriteria->equals($criteria)) {
				$this->collSftUsuarios = SftUsuarioPeer::doSelectJoinSftOrganismo($criteria, $con, $join_behavior);
			}
		}
		$this->lastSftUsuarioCriteria = $criteria;

		return $this->collSftUsuarios;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collSftOrganismos) {
				foreach ((array) $this->collSftOrganismos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collSftUsuarios) {
				foreach ((array) $this->collSftUsuarios as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collSftOrganismos = null;
		$this->collSftUsuarios = null;
			$this->aSftTipoDocIdentificacion = null;
			$this->aGenPais = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseSftPersona:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseSftPersona::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseSftPersona
