<?php


/**
 * Skeleton subclass for performing query and update operations on the 'nfg_invitado' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/31/11 19:09:32
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class NfgInvitadoPeer extends BaseNfgInvitadoPeer {

} // NfgInvitadoPeer
