<?php



/**
 * Skeleton subclass for performing query and update operations on the 'nfg_localidad' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * Fri Nov 18 20:09:27 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class NfgLocalidadQuery extends BaseNfgLocalidadQuery {

} // NfgLocalidadQuery
